source "https://rubygems.org/"

gem "cucumber"
gem "rspec"
gem "capybara"
gem "selenium-webdriver"
gem "capybara-screenshot"
gem 'launchy', '~> 3.0.1'
gem 'childprocess', '~> 5.0'
gem 'allure-cucumber'
